spring:
  application:
    name: academy
  datasource:
    url: jdbc:postgresql://localhost:5432/test_academy
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/academy-glm-realm
          jwk-set-uri: http://localhost:8181/realms/academy-glm-realm/protocol/openid-connect/certs

eureka:
  instance.hostname: localhost
  client:
    serviceUrl.defaultZone: http://eureka:password@localhost:8761/eureka/
    # serviceUrl.defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0