version: '3.8'

services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - erudia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=native

  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - erudia-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=eureka-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:password@eureka-service:8761/eureka/
      - SPRING_SECURITY_USER_NAME=eureka
      - SPRING_SECURITY_USER_PASSWORD=password
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - erudia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:password@eureka-service:8761/eureka/
      - KEYCLOAK_SERVER_URL=http://keycloak:8181
      - KEYCLOAK_REALM=academy-glm-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8181/realms/academy-glm-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8181/realms/academy-glm-realm/protocol/openid-connect/certs
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX_RIBBON=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_LOADBALANCER=DEBUG
    extra_hosts:
      - "host.docker.internal:host-gateway"

  academy-service-1:
    build:
      context: ./academy-service
      dockerfile: Dockerfile
    container_name: academy-service-1
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - erudia-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - SPRING_APPLICATION_NAME=academy
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:password@eureka-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - "EUREKA_INSTANCE_INSTANCE_ID=academy:$${random.uuid}"
      - DB_USERNAME=apiclient-erudia
      - DB_PASSWORD=postgres
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

  academy-service-2:
    build:
      context: ./academy-service
      dockerfile: Dockerfile
    container_name: academy-service-2
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_started
    networks:
      - erudia-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - SPRING_APPLICATION_NAME=academy
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:password@eureka-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - "EUREKA_INSTANCE_INSTANCE_ID=academy:$${random.uuid}"
      - DB_USERNAME=apiclient-erudia
      - DB_PASSWORD=postgres
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

  keycloak:
    image: keycloak_glm:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8181:8080"
    command: /opt/keycloak/bin/kc.sh start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - erudia-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  keycloak_data:
    external: true

networks:
  erudia-network:
    driver: bridge