spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://postgres-academy:5432/academy
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
    ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka
    # serviceUrl.defaultZone: http://eureka:password@localhost:8761/eureka