spring:
  application:
    name: academy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.72.214.106:5432/academy
    username: apiclient-erudia
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8181/realms/academy-glm-realm
          jwk-set-uri: http://host.docker.internal:8181/realms/academy-glm-realm/protocol/openid-connect/certs


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-service:8761/eureka/

server:
  port: 0
