eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-service:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    config:
      uri: http://config-service:8888