app:
  eureka-server: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-service:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/academy-glm-realm
          jwk-set-uri: http://keycloak:8181/realms/academy-glm-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: academy
          uri: lb://academy
          predicates:
            - Path=/api/academy/**
        - id: eureka
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/web
          filters: SetPath=/
        - id: eureka-static
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/**
