spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway


logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
          reactive:
            handler: DEBUG
        cloud:
          gateway: DEBUG

