spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway


jwt.auth.converter.resource-id: spring-cloud-client
jwt.auth.converter.principle-attribute: preferred_username
logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
          reactive:
            handler: DEBUG
        cloud:
          gateway: DEBUG

