eureka:
  client:
    register-with-eureka: true

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: academy
          uri: http://localhost:8090
          predicates:
            - Path=/api/academy/**
