server.port: 8080
app:
  eureka-server: localhost
eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://eureka:password@localhost:8761/eureka/
  # serviceUrl.defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    org.keycloak: DEBUG
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO



spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      ## Academy Service
      routes:
        - id: academy
          uri: lb://academy
          predicates:
            - Path=/api/academy/**

        ## Eureka Service
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters: SetPath=/

        ## Eureka Service Static Web
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  security:
    user:
      name: eureka
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/academy-glm-realm
          jwk-set-uri: http://localhost:8181/realms/academy-glm-realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id: spring-cloud-client
jwt.auth.converter.principle-attribute: sub